server:
  port: 8072
  
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
      
spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/usr/**
        filters:
        - RewritePath=/usr/(?<path>.*), /v1/user/$\{path}
        - RemoveRequestHeader= Cookie,Set-Cookie
        
      - id: tribe-service
        uri: lb://tribe-service
        predicates:
        - Path=/mtg/**
        filters:
        - RewritePath=/mtg/(?<path>.*), /v1/$\{path}
        - RemoveRequestHeader= Cookie,Set-Cookie
        
management:
  endpoints:
    web:
      exposure:
        include: "*"